##########################################################
# v1.1 Github Actions Pipelines
# Template - Tf Deploy
# Yaml is exact similar to v1.1 minus validate and plan
##########################################################

name: 'v1.2 - Deploy'

on: [workflow_dispatch]

jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_SPI_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_SPI_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: 'Terraform Format'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.1.2
        tf_actions_subcommand: 'fmt'
        tf_actions_working_dir: "./terraform"
        
    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.1.2
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: "./terraform"

    - name: Terraform Apply
      if: github.ref == 'refs/heads/master'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.1.2
        tf_actions_subcommand: 'apply'
        tf_actions_working_dir: "./terraform"

